---
title: "p8105_hw6_hm2946"
author: "min"
date: "2022-12-02"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(p8105.datasets)
set.seed(1)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

*Download the data*
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

*Plot r.squared*
```{r}
rsquared_weather = 
  weather_df %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x) ),
    results = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(results)

rsquared_weather %>% 
  ggplot(aes(x = r.squared)) + geom_density()
```
*The graph is skewed to the left and has some outliers.*

```{r}
rsquared_quantiles = 
  rsquared_weather %>% 
  select(r.squared) %>%
  arrange(r.squared)

rsquared_quantiles[c(25,975),]
```
*95% CI for r.squared is (0.895,0.927)*

*Plot log_b0b1*
```{r}
log_weather = 
  weather_df %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x) ),
    results = map(models, broom::tidy)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  select(id = `.id`, term, estimate) %>% 
  pivot_wider(
    names_from = term, 
    values_from = estimate) %>% 
  rename(beta0 = `(Intercept)`, beta1 = tmin) %>% 
  mutate(log_b0b1 = log(beta0 * beta1))

log_weather %>% 
  ggplot(aes(x = log_b0b1)) + geom_density()
```
*The graph is skewed to the left and has some outliers.*

```{r}
log_quantiles = 
  log_weather %>% 
  select(log_b0b1) %>%
  arrange(log_b0b1)

log_quantiles[c(25,975),]
```
*95% CI for log is (1.96,2.06)*

## Problem 2

```{r}
homi_cide = read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city,state,sep = ","),
    resolved = as.numeric(disposition == "Closed by arrest"),
    victim_age = as.numeric(victim_age),
    victim_race = fct_relevel(victim_race, "White")) %>% 
  select(city_state, resolved, victim_age, victim_race, victim_sex) %>% 
  filter(victim_race == c("White","Black")) %>% 
  filter(city_state != c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL"))
```
